"""beneficiaries

Revision ID: 6afe85f2dcc3
Revises: 1b4d3c53c780
Create Date: 2022-04-08 08:48:11.045849

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6afe85f2dcc3'
down_revision = '1b4d3c53c780'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beneficiary',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('surname', sa.String(), nullable=True),
    sa.Column('company_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_beneficiary_id'), 'beneficiary', ['id'], unique=False)
    op.drop_table('company_person')
    op.add_column('person', sa.Column('company_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key('company_fk', 'person', 'company', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('company_fk', 'person', type_='foreignkey')
    op.drop_column('person', 'company_id')
    op.create_table('company_person',
    sa.Column('company_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('person_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name='company_person_company_id_fkey'),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], name='company_person_person_id_fkey'),
    sa.PrimaryKeyConstraint('company_id', 'person_id', name='company_person_pkey')
    )
    op.drop_index(op.f('ix_beneficiary_id'), table_name='beneficiary')
    op.drop_table('beneficiary')
    # ### end Alembic commands ###
