"""company-schema-update

Revision ID: 6e5a8c476bd4
Revises: 8d1816033f18
Create Date: 2022-03-07 13:35:27.456444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e5a8c476bd4'
down_revision = '8d1816033f18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('zip', sa.String(), nullable=True))
    op.add_column('company', sa.Column('finstat_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('company', 'registry_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('registry_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('company', 'finstat_at')
    op.drop_column('address', 'zip')
    # ### end Alembic commands ###
