"""147-token-updates

Revision ID: 8d1816033f18
Revises: 5fccc7d1f780
Create Date: 2022-03-04 15:28:52.018971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d1816033f18'
down_revision = '5fccc7d1f780'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('requested_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('person', sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'verified_at')
    op.drop_column('person', 'requested_at')
    # ### end Alembic commands ###
