"""dic

Revision ID: ec8d111d46c4
Revises: 38f2eb79ad3e
Create Date: 2022-03-20 14:26:29.356097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec8d111d46c4'
down_revision = '38f2eb79ad3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('dic', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'dic')
    # ### end Alembic commands ###
