"""schema update

Revision ID: f31be80ddbad
Revises: 6e5a8c476bd4
Create Date: 2022-03-08 05:15:01.582514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f31be80ddbad'
down_revision = '6e5a8c476bd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'email')
    # ### end Alembic commands ###
